# example netlify.toml

[build]
  command = "npx @11ty/eleventy"
  publish = "_site"

[dev]
framework = "#static"
command = "npx @11ty/eleventy --quiet --watch"

[[edge_functions]]
function = "eleventy-edge"
path = "/search/"

[[edge_functions]]
function = "filter-search-data"
path = "/search-data.json"