# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "_site"

[[edge_functions]]
function = "eleventy-edge"
path = "/search/"

[[edge_functions]]
function = "filter-search-data"
path = "/search-data.json"